
[enchantability]
	#how much each point of enchantability in the item will add to its enchantment point pool
	#Range: 0.0 ~ 1.7976931348623157E308
	"points per enchantability" = 0.5
	#if the number of enchantment points falls within this distance to a whole number, it will be rounded to the whole number instead. This allows you to have clean 1/3 or 1/7 for the incremental cost of enchantments.
	#Range: 0.0 ~ 1.0
	granularity = 0.1
	#how many enchantment points an item starts with
	#Range: 0.0 ~ 1.7976931348623157E308
	"base points" = 10.0
	#the default cost to add a new enchantment onto an item.
	#Range: 0.0 ~ 1.7976931348623157E308
	"base cost" = 0.0
	#the default cost to add one level to any existing enchantment on the item. An enchantment with level 1 will apply both the base cost and the incremental cost, once each.
	#Range: 0.0 ~ 1.7976931348623157E308
	"incremental cost" = 1.0
	#Items that have their own enchantment point cap. Format is name, base enchantability, increment per extra point of enchantability.
	"custom items" = ["kubejs:allthemodium_mesh, 20, 1", "kubejs:vibranium_mesh, 20, 1", "matc:inferium_crystal, 2, 0", "matc:prudentium_crystal, 2, 0", "matc:tertium_crystal, 2, 0", "matc:imperium_crystal, 2, 0", "matc:supremium_crystal, 2, 0"]
	#It's really irritating how nightconfig doesn't keep the entries in separate lines, but alas. Define enchantments here. Format is name, base cost, incremental cost.
	enchantments = ["minecraft:mending, 8, 0", "minecraft:sharpness, 1, 1"]
	#Enchantments that should be blacklisted. Format is name. Examples: ["minecraft:mending", "minecraft:sharpness"]
	"blacklisted enchantments" = []